name: Build libcob and libgmp
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "Setup Emscripten"
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest

    - name: Build libgmp wasm
      run: |
        source ./emsdk/emsdk_env.sh
        mkdir -p ${HOME}/opt
        wget https://gmplib.org/download/gmp/gmp-6.1.2.tar.xz
        tar xvf gmp-6.1.2.tar.xz
        cd gmp-6.1.2
        emconfigure ./configure --disable-assembly --host none --prefix=${HOME}/opt
        make
        make install

    - name: Install dependencies
      run: |
        sudo apt-get install autopoint gettext
    
    - name: Build libcob wasm
      run: |
        source ./emsdk/emsdk_env.sh
        mkdir -p ${HOME}/opt
        wget http://sourceforge.net/projects/open-cobol/files/gnu-cobol/3.0/gnucobol-3.0-rc1.tar.gz
        tar xvf gnucobol-3.0-rc1.tar.gz
        cd gnucobol-3.0-rc1
        sed -i '14680,14868d' configure # Delete GMP checks
        sed -i '515,582d' configure.ac # Delete GMP checks

        autoreconf -f -i
        emconfigure ./configure --with-db=false --disable-assembly --prefix=${HOME}/opt --includedir=${HOME}/opt/include
        make defaults.h
        cd libcob
        emmake make INCLUDES=-I${HOME}/opt/include
        make install
    
    - name: Combine libraries
      run : |
        source ./emsdk/emsdk_env.sh
        mkdir -p publish
        cd publish
        ar -x ${HOME}/opt/lib/libcob.a
        ar -x ${HOME}/opt/lib/libgmp.a
        ../emsdk/upstream/bin/wasm-ld *.o -o libcob.so --relocatable --no-entry
        rm *.o
        cp ../gnucobol-3.0-rc1/libcob.h .

    - name: Release dependencies
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: publish/*
        file_glob: true
        tag: 1.0
        overwrite: true
        body: "Wasm library dependencies"